### ISSUE TITLE
Cannot add default values to parameters

### ISSUE THREAD

**Issue by epotter2297** [ecyrbe/zodios-openapi#35]
Trying to create an api with a parameter like this
```js
{
  name: 'limit',
  type: 'Query',
  schema: z.number().default(10),
},
```
Gives me this error when the openapi doc is generated
```
TypeError: r.schema.unwrap is not a function
  at A (file:///Users/24g/Documents/monorepo-prisma-example/node_modules/.pnpm/@zodios+openapi@10.4.2_ht6ecrqrdz2wigzfmrk6d36cja/node_modules/@zodios/openapi/lib/index.mjs:4:1838)
  at q (file:///Users/24g/Documents/monorepo-prisma-example/node_modules/.pnpm/@zodios+openapi@10.4.2_ht6ecrqrdz2wigzfmrk6d36cja/node_modules/@zodios/openapi/lib/index.mjs:4:2544)
  at file:///Users/24g/Documents/monorepo-prisma-example/apps/project-a/src/app.ts:11:18
  at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
  at async loadESM (node:internal/process/esm_loader:91:5)
  at async handleMainPromise (node:internal/modules/run_main:65:12)
```

**Comment by ecyrbe** [comment]
this is now fixed in `@zodios/openapi` [v10.4.3](https://github.com/ecyrbe/zodios-openapi/releases/tag/v10.4.3)
